[uwsgi]
manage-script-name = true
module = camera_service.wsgi:app

master = true

#chdir = /project

processes = 1
threads = 1
enable-threads = true
reload-mercy = 1
worker-reload-mercy = 1


socket = 0.0.0.0:5000
protocol = http

;chmod-socket = 666
;vacuum = true

#buffer-size = 32768

die-on-term = true

plugin = python3
;py-autoreload = false

;wsgi-disable-file-wrapper = true
;venv = /project/venv

;uid = camserv
;gid = camserv



