[uwsgi]
module = ai_service.wsgi
callable = app
master = true
processes = 1
;chdir = /home/appuser/repos/planogram-ai-service
socket = 0.0.0.0:7552
protocol = http
buffer-size = 32768
plugin = python3
wsgi-disable-file-wrapper = true
;uid = 
;gid = 
