class_to_sku = {0: "Unknown",
                1: "ANANAS KAWAŁKI KUBEK 200G",
                2: "ANTIPASTI MIX PAPRYCZEK PERLA 150G",
                3: "BAGIETKA",
                4: "BAGIETKA ANDALUZ. TOMCIO PALUCH 210G",
                5: "BAGIETKA HOT STR TOMCIO PALUCH 240G",
                6: "BAGIETKA JAJKO SZYNKA FOODMAKERS 225G",
                7: "BAGIETKA KATALOŃSKA 225G TOM PAL",
                8: "BAGIETKA Z MASŁEM I CZOSNKIEM 175G",
                9: "BAGIETKA ŚRÓDZIEMNOMOR 250G TOM PA",
                10: "BRACIA SADOWNICY",
                11: "CHEESEBURGER WOLOWY 165G",
                12: "DANIE DYNIOWE CURRY Z INDYK I RYŻ. 400G",
                13: "DANIE KUR.GREEN CURRY Z RYŻ.JAŚ.350G",
                14: "DANIE KURCZ RED CURRY Z RYŻ.JAŚ. 350G",
                15: "DANIE MASSAMAN CURRY Z RYŻ. JAŚ.350G",
                16: "DANIE OBIADOWE",
                17: "DANIE OSTRA WOŁOW Z KASZĄ GRYCZ 400G",
                18: "DANIE WOŁOWINA Z MARCHEWK PUREE 400G",
                19: "DELICADE",
                20: "DESER CHIA Z MANGO 140G",
                21: "FOODINI",
                22: "GRZESKOWIAK",
                23: "HUMMUS CZARNUSZKA POMIDOR 110G",
                24: "HUMMUS KLASYCZNY PAPRYKOWY MIX 110G",
                25: "HUMMUS Z FALAFELEM 220G",
                26: "INDYK Z GRILLOWANYMI ZIEMNIAKAMI 350G",
                27: "JEDRUS",
                28: "JOGURTOWY INDYK Z KOMOSĄ RYŻOWĄ 360G",
                29: "KACZKA Z WARZYWAMI I MAKARONEM 400G",
                30: "KAJZERKA KEBAB 137G",
                31: "KAJZERKA Z JAJKIEM TOMCIO PALUCH 120G",
                32: "KAJZERKA Z SEREM TOMCIO PALUCH 122G",
                33: "KAJZERKA Z SZYNKĄ TOMCIO PALUCH 116G",
                34: "KANAPKA TROJKAT",
                35: "KANAPKA TRÓJ CEZAR TOMCIO PALUCH 205G",
                36: "KANAPKA TRÓJ JAJKO BEKON TOMCIO 220G",
                37: "KANAPKA TRÓJ KURC.Z WARZ.FOODMAKERS 210G",
                38: "KANAPKA TRÓJ SZYN TOMCIO PALUCH 210G",
                39: "KANAPKA TRÓJ TUŃCZ.JAJKO FOODMAKERS 210G",
                40: "KANAPKA TRÓJ. Z ŁOSOSIEM TOM.PAL 190G",
                41: "KANAPKA TRÓJ.TOSKANSKA TOM.PAL 190G",
                42: "KANAPKI CHICKEN DUO 2 SZT 270G",
                43: "KAWA COLD BREW CLASSIC 220ML",
                44: "KAZJERKA",
                45: "KOTLET CORDON BLEU 250G",
                46: "KOTLET DROBIOWY Z MARCHEWKĄ 400G",
                47: "KOTLET MIELONY WIEPRZ BURACZKI 400G",
                48: "KROKIETY Z KAPUSTĄ I GRZYB 400G",
                49: "KROKIETY Z MIĘSEM 400G U JĘDRUSIA",
                50: "KULKI RYŻOWE MALINA PORZECZKA 125G",
                51: "KULKI RYŻOWE Z MANGO I MARKUJĄ 125G",
                52: "KURCZAK AZJATYCKI",
                53: "KURCZAK GONG BAO 400G",
                54: "KURCZAK INDYJSKI JALFREZI Z RYŻEM 450G",
                55: "KURCZAK TIKKA MASALA Z RYŻEM 450G",
                56: "KURCZAK W GALARECIE 150G",
                57: "KURCZAK W SOSIE SŁODKO-KWAŚNYM 400G",
                58: "KURCZAK WARZYWA Z CIECIERZYCĄ 300G",
                59: "KURCZAK Z SOSEM CURRY I RYŻEM 430G",
                60: "KURCZAK Z WARZYWNĄ ZAPIEKANKĄ 440G",
                61: "LASAGNE BOLOGNESE COME A CASA 400G",
                62: "LEMONIADA WYCISK CYTRYNOWA 400ML",
                63: "LEMONIADA WYCISK GREJPF. TRUSK 400ML",
                64: "MAKARON PENNE PEPPERONI 400G",
                65: "MAKARON SOJOWY Z KURCZAKIEM 440G",
                66: "MAKARON Z SOSEM POMIDOROWYM 300G",
                67: "MIESO W GALARECIE",
                68: "MINI BAGIETKA SZYNKA JAJKO 181G",
                69: "MUS GOOD MOOD",
                70: "MUS JABŁKO-MANGO ZIARN GOOD MOOD 130G",
                71: "MUS JABŁKOWY GOOD MOOD 130G",
                72: "NALEŚNIKI ARRABIATA Z KURCZAKIEM 200G",
                73: "NALEŚNIKI Z SEREM 300G",
                74: "NALEŚNIKI Z SEREM I CZEKOLADĄ 200G",
                75: "NAPÓJ SOTI BIO NAT ROIBOS IMBIR 340ML",
                76: "NAPÓJ SOTI BIO NAT.MIĘTA TRAWA CYT.340ML",
                77: "NUGGETSY PANIEROWANE 250G + SOS",
                78: "OLIWKI",
                79: "OLIWKI ZIELONE CHILLI 90G",
                80: "OLIWKI ZIELONE W ZIOŁACH 90G",
                81: "ONIGIRI",
                82: "ONIGIRI KURCZAK PREMIUM 120G",
                83: "ONIGIRI TUŃCZYK PREMIUM 120G",
                84: "ONIGIRI ŁOSOŚ PREMIUM 120G",
                85: "OWOCE KAWALKI",
                86: "OWOCE MIX KAWAŁKI KUBEK 200G",
                87: "OWSIANKA",
                88: "OWSIANKA KOKOS MANGO MARAKU 210G",
                89: "OWSIANKA KOKOS WIŚNIA 210G",
                90: "PANIEROWANE",
                91: "PANINI",
                92: "PIECZONY SCHAB W SOSIE 400G",
                93: "PIEROGI DROBIOWE Z SMAŻ CEBUL 320G",
                94: "PIEROGI RUSKIE 400G U JĘDRUSIA",
                95: "PIEROGI RUSKIE W KUBKU 320G",
                96: "PIEROGI W KUBKU",
                97: "PIEROGI Z MASCARPONE I SOS JAGOD 300G",
                98: "PIEROGI Z MIĘSEM 400G U JĘDRUSIA",
                99: "PIEROGI Z MIĘSEM W KUBKU 320G",
                100: "PIZZA",
                101: "PIZZA SEROWA 430G",
                102: "PIZZA Z SZYNKĄ I PIECZ 360G",
                103: "PIZZINA",
                104: "PLACKI ZIEMNIACZANE 400G",
                105: "PLACKI ZIEMNIACZANE Z GULASZEM 350G",
                106: "POLĘDWICZKI PANIEROWANE 200G + SOS",
                107: "RACUCHY Z JABŁKAMI 300G",
                108: "ROLADA WOŁOWA 400G",
                109: "ROŚLINNY BURGER 170G",
                110: "SALATKA AL DENTE",
                111: "SALATKA DEGA",
                112: "SALATKA LUNCHBOX",
                113: "SALATKA POKEBOWL",
                114: "SALATKA SHAKER",
                115: "SALATKA Z HUMMUSEM",
                116: "SAŁATKA AL DENTE KURCZ. BROK.150G LISNER",
                117: "SAŁATKA AL DENTE SUSZ.POM. 150G LISNER",
                118: "SAŁATKA AMERYKAŃSKA TO GO 200G GRZEŚK",
                119: "SAŁATKA BULGUR CIEC. POMIDOR 200G GRZEŚK",
                120: "SAŁATKA BULGUR Z HUMMUSEM 180G",
                121: "SAŁATKA DEGA JARZYNOWA 140G",
                122: "SAŁATKA DEGA JARZYNOWA Z PAPRYKĄ 140G",
                123: "SAŁATKA DEGA KEBAB 140G",
                124: "SAŁATKA DEGA PO PEKIŃSKU Z SZYNKĄ 140G",
                125: "SAŁATKA KEBAB TO GO 200G GRZEŚKOWIAK",
                126: "SAŁATKA KUSKUS Z HUMMUSEM 180G",
                127: "SAŁATKA LUNCHBOX KURCZAK SER DK 195G",
                128: "SAŁATKA LUNCHBOX ROMANTICA DK 155G",
                129: "SAŁATKA MAKARON. Z PAPRYKĄ TO GO 200G",
                130: "SAŁATKA PROTEINOWA QUINOA DK 180G",
                131: "SAŁATKA SHAKER KASZA KURCZAK DK 150G",
                132: "SAŁATKA SHAKER MOZZARELLA PESTO 130G",
                133: "SAŁATKA Z KREWETKAMI POKE BOWL 330G",
                134: "SAŁATKA Z ŁOSOSIEM POKE BOWL 330G",
                135: "SKRZYDEŁKA PANIEROWANE 250G + SOS",
                136: "SMOOTHIE FOODINI BEZTR.CZERWONY 250ML",
                137: "SMOOTHIE FOODINI EGZOTYCZ.ŻÓŁTY 250ML",
                138: "SMOOTHIE FOODINI GAZPACHO 250ML",
                139: "SMOOTHIE FOODINI JOGURT RÓŻOWY 250ML",
                140: "SMOOTHIE FOODINI JOGURT ŻÓŁTY 250ML",
                141: "SMOOTHIE FOODINI KOJĄCO ZIELONY 250ML",
                142: "SMOOTHIE FOODINI PRZYJEM.KREMOW.250ML",
                143: "SMOOTHIE FOODINI RAJSKO KREMOWY 250ML",
                144: "SMOOTHIE FOODINI SMACZ. ZIELONY 250ML",
                145: "SMOOTHIE FOODINI SŁONECZ. ŻÓŁTY 250ML",
                146: "SNACKI WARZYWA & HUMMUS DK 230G",
                147: "SOK JABŁKO-MARCHEW BRACIA SAD. 0.25L",
                148: "SOK JABŁKO-PIGWA BRACIA SAD. NFC 0.25L",
                149: "SOK MARCHWIOWY Z MIODEM 330ML DELICADE",
                150: "SOK WYCISK AWOCADO SZPINAK 250ML",
                151: "SOK WYCISK BURAK MALINA 250ML",
                152: "SOK WYCISK GRAPEFRUIT 250ML",
                153: "SOK WYCISK JABŁKO CYTRYNA MIĘTA 250ML",
                154: "SOK WYCISK MARCHANANASKURKUMA 250ML",
                155: "SOK WYCISK MARCHEW JABŁKO 250ML",
                156: "SOK WYCISK POMARAŃCZA GREJPFRUT 250ML",
                157: "SOK WYCISK POMARAŃCZOWY 250ML",
                158: "SOK WYCISK POMARMARAKUJAMACA 250ML",
                159: "SOK WYCISK TRUSKAWKA MALIN ACAI 250ML",
                160: "SOK Z MARCHWI I BANANA 330ML DELICADE",
                161: "SOTI",
                162: "SPAGHETTI",
                163: "SPAGHETTI BOLOGNESE 400G",
                164: "SPAGHETTI CARBONARA 400G",
                165: "SPORTFOOD",
                166: "SUSHI",
                167: "SUSHI KATSUMI 420G",
                168: "SUSHI NORIKO 225G",
                169: "SUSHIBOX PREMIUM TOKYO TEY 245G",
                170: "SZAMAMM BIALE TACKI",
                171: "SZAMAMM OBIADOWE",
                172: "TORTILLA ARABSKA 250G KONSPOL",
                173: "TORTILLA KONSPOL",
                174: "TORTILLA LATYNOSKA 250G KONSPOL",
                175: "TOST",
                176: "WEGETARIAŃSKI PAD THAI Z TOFU 320G",
                177: "WIEPRZOWINA W GALARECIE 150G",
                178: "WODA NAŁĘCZOWIANKA 0.5L NGAZ PET",
                179: "WYCISK",
                180: "ZAPIEKANKA VIRTU",
                181: "ZAPIEKANKA Z PIECZARKAMI VIRTU 235G",
                182: "ZAPIEKANKA Z SZYNKĄ VIRTU 235G",
                183: "ZK PANINI KURCZAK CHŁODZONE 185G",
                184: "ZK PANINI SER SZYNKA CHŁODZONE 175G",
                185: "ZK PANINI Z WARZYW GRILL CHŁOD 170G",
                186: "ZK PIZZINA SALAMI 170G",
                187: "ZK PIZZINA SZYNKA 170G",
                188: "ZK TOST Z KEBABEM Z KURCZAKA 130G",
                189: "ZK TOST Z SZYNKĄ I SEREM 115G",
                190: "ZUPA",
                191: "ZUPA KREM Z BIAŁYCH WARZYW 390G",
                192: "ZUPA KREM Z POMIDORA 350G",
                193: "ZUPA MAROKAŃSKA 380G",
                194: "ZUPA OGÓRKOWA 350G",
                195: "ZUPA TAJSKA Z KURCZAKIEM 380G"}
