"""
Tools for manipulating JSON file generated by VGG Image Annotator
http://www.robots.ox.ac.uk/~vgg/software/via/
"""
import itertools
import json
import os
import re
import shutil
import cv2
import numpy as np

from shapely import geometry

from vision.aug.utils import order_points


def count_region_attribute_values(file_path, attribute_name, values_list):
    values_counter_dict = dict((value, 0) for value in values_list)
    with open(file_path) as data_file:
        data = json.load(data_file)
        for file in data:
            for region in data[file]["regions"]:
                if attribute_name in data[file]["regions"][region]["region_attributes"]:
                    values_counter_dict[data[file]["regions"][region]["region_attributes"][attribute_name]] += 1
    return values_counter_dict


def print_values_counter(values_counter_dict, required_number=100):
    """
    Prints sorted dictionary of values' count and progress calculation

    :param values_counter_dict: Dictionary with values' count (e.g. {"label_1" : 30, "label_2" : 2})
    :param required_number: How many values are required, used to calculate progress
    :return: Nothing
    """
    for value in sorted(values_counter_dict.items()):
        print("'{0}' \t{1}\t\t/{2}\t{3:3.2f}%".format(value[0], value[1], required_number,
                                                      100 * value[1] / required_number))
    print("Total: \t{0}\t/{1}\t{2:3.2f}%".format(sum(values_counter_dict.values()),
                                                 len(values_counter_dict) * required_number,
                                                 100 * sum(values_counter_dict.values()) /
                                                 (len(values_counter_dict) * required_number)))


def load_json_file(file_path):
    print("Opening: {0}".format(file_path))
    with open(file_path) as data_file:
        data = json.load(data_file)
    return data


def save_json_file(new_file_path, data):
    print("INFO Saving JSON under: {0}".format(new_file_path))
    with open(new_file_path, "w") as new_file:
        json.dump(data, new_file)


def copy_data_by_attribute_value(file_path, image_dir, target_dir, attribute_name, values_list, output_path=None):
    copied_data_dict = {}
    data = load_json_file(file_path)
    file_counter = 0
    for file in data:
        for region in data[file]["regions"]:
            if attribute_name in data[file]["regions"][region]["region_attributes"]:
                if data[file]["regions"][region]["region_attributes"][attribute_name] in values_list:
                    image_name = file.split(".")[0] + ".jpg"
                    shutil.copy2(os.path.join(image_dir, image_name), target_dir)
                    copied_data_dict[file] = data[file]
                    file_counter += 1
                    break
    print("Copied {0} files".format(file_counter))

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path), "copied_by_value.json")
    save_json_file(output_path, copied_data_dict)


def trim_regions_by_attribute_value(file_path, attribute_name, value_list, output_path=None):
    data = load_json_file(file_path)
    for file in data:
        to_remove = [region for region in data[file]["regions"]
                     if attribute_name in data[file]["regions"][region]["region_attributes"] and
                     data[file]["regions"][region]["region_attributes"][attribute_name] not in value_list]
        for region in to_remove:
            del data[file]["regions"][region]

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path), "trimmed_regions.json")
    save_json_file(output_path, data)


def change_region_attribute_values(file_path, attribute_name, attribute_values_dict, output_path=None):
    data = load_json_file(file_path)
    for file in data:
        for region in data[file]["regions"]:
            if attribute_name in data[file]["regions"][region]["region_attributes"]:
                value = data[file]["regions"][region]["region_attributes"][attribute_name]
                if value in list(attribute_values_dict.keys()):
                    data[file]["regions"][region]["region_attributes"][attribute_name] = \
                        attribute_values_dict[value]

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path), "changed_values.json")
    save_json_file(output_path, data)


def add_attribute_with_value(file_path, attribute_name, attribute_value, output_path=None):
    data = load_json_file(file_path)
    for file in data:
        for region in data[file]["regions"]:
            data[file]["regions"][region]["region_attributes"][attribute_name] = attribute_value

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path), "added_attribute.json")
    save_json_file(output_path, data)


def merge_regions_lists(file_path_one, file_path_two, output_path=None):
    data_one = load_json_file(file_path_one)
    data_two = load_json_file(file_path_two)
    for file in data_one:
        if file in data_two.keys() and data_two[file]["regions"]:
            regions_list_length = len(data_one[file]["regions"])
            for region in data_two[file]["regions"]:
                new_region_key = str(int(region) + regions_list_length)
                data_one[file]["regions"][new_region_key] = data_two[file]["regions"][region]

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path_one), "merged_regions.json")
    save_json_file(output_path, data_one)


def merge_files_list(files_paths, output_path=None):
    last_path = files_paths.pop()
    data = load_json_file(last_path)
    for path in files_paths:
        data.update(load_json_file(path))

    output_path = output_path if output_path else os.path.join(os.path.dirname(last_path), "merged_files.json")
    save_json_file(output_path, data)


def rename_region_attribute(file_path, attributes_names_dict, output_path=None):
    data = load_json_file(file_path)
    for file in data:
        for region in data[file]["regions"]:
            for attribute in data[file]["regions"][region]["region_attributes"]:
                if attribute in list(attributes_names_dict.keys()):
                    data[file]["regions"][region]["region_attributes"][attributes_names_dict[attribute]] = \
                        data[file]["regions"][region]["region_attributes"].pop(attribute)

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path), "renamed_attributes.json")
    save_json_file(output_path, data)


def remove_filenames_without_regions(file_path, output_path=None):
    data = load_json_file(file_path)
    to_remove = [file for file in data if not data[file]["regions"]]
    for file in to_remove:
        del data[file]

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path), "removed_empty.json")
    save_json_file(output_path, data)


def find_incorrect_coordinates_length(file_path, coordinates_length):
    data = load_json_file(file_path)
    incorrect_files = []
    for file in data:
        for region in data[file]["regions"]:
            if len(data[file]["regions"][region]["shape_attributes"]["all_points_x"]) != coordinates_length:
                incorrect_files.append([file, data[file]["regions"][region]["shape_attributes"]["all_points_x"]])
    return incorrect_files


def rename_json_keys(json_data):
    def split_size(s):
        return re.split(r"(\d+)", s)
    json_keys = list(json_data.keys())
    for json_key in json_keys:
        name, ext = os.path.splitext(json_key)
        new_key = name + split_size(ext)[0]
        json_data[new_key] = json_data.pop(json_key)


def get_region_points(region):
    assert len(region["shape_attributes"]["all_points_x"]) in (4, 5)

    points = list(zip(region["shape_attributes"]["all_points_x"][:4],
                      region["shape_attributes"]["all_points_y"][:4]))
    return np.array(points, dtype=np.int32)


def get_region_bounding_rect(region, points=None):
    """ Return region's bounding rect """
    if points is None:
        points = get_region_points(region)
    return cv2.boundingRect(points)


def extract_json_data_multilabel(json_data, img_name, class_name_map, min_size=16):
    """ Extract data needed to build original dataset """
    products = []
    for _, region in json_data[img_name]["regions"].items():
        region_classes = region["region_attributes"]["label"].split(",")
        region_coords = get_region_points(region)
        
        # ignore very small boxes
        _, _, w, h = cv2.boundingRect(region_coords)
        if w < min_size or h < min_size:
            continue
        
        region_classes = [i for r in region_classes for i in class_name_map[r.strip()]]
        region_classes = list(set(region_classes))

        # ugly hack related to different formats between classifier and detector data
        class_name = "box" if region["region_attributes"]["label"] == "1" else region["region_attributes"]["label"]

        product = {"class": region_classes,
                   "class_name": class_name,
                   "coordinates": order_points(region_coords).tolist()}
        products.append(product)

    return products


def fix_multiplied_points(file_path, output_path=None):
    import numpy as np
    json_data = load_json_file(file_path)

    for k, v in json_data.items():
        for j, region in v["regions"].items():
            pts_len = len(region["shape_attributes"]["all_points_x"])
            if pts_len != 5 and pts_len != 4:
                points = list(zip(region["shape_attributes"]["all_points_x"],
                                  region["shape_attributes"]["all_points_y"]))
                areas = {}
                for i in itertools.combinations(points, 4):
                    poly = geometry.Polygon(i)
                    areas[poly.area] = i

                _, right_coords = sorted(areas.items(), reverse=True)[0]
                right_coords = order_points(np.array(right_coords)).tolist()
                new_x, new_y = zip(*right_coords)
                json_data[k]["regions"][j]["shape_attributes"]["all_points_x"] = new_x
                json_data[k]["regions"][j]["shape_attributes"]["all_points_y"] = new_y

    output_path = output_path if output_path else os.path.join(os.path.dirname(file_path), "fixed_points.json")
    save_json_file(output_path, json_data)


if __name__ == "__main__":
    # sample usage
    trim_regions_by_attribute_value("/tytan/raid/drugs-counter/data/tabcin_gripex/labels-json/_all_classes_528.json", "label", ["1", "2"])
    merge_regions_lists("/tytan/raid/drugs-counter/data/tabcin_gripex/labels-json/trimmed_regions.json", "/tytan/raid/drugs-counter/data/tabcin_gripex/labels-json/__all_stock.json")
